#!/bin/bash

/usr/bin/busybox --install -s /usr/bin

for arg in $(cat /proc/cmdline); do
    case "${arg}" in
        root=*)
            root="${arg#root=}"
            ;;
    esac
done

if [[ -z "${root}" ]]; then
    exit 0
fi

mkdir -p /run/systemd/generator/initrd-root-fs.target.wants
cat > /run/systemd/generator/mount-sysroot.service <<EOF
[Unit]
Before=initrd-root-fs.target
After=systemd-udev-trigger.service systemd-udev-settle.service
OnFailure=emergency.target
DefaultDependencies=no

[Service]
Type=oneshot
RemainAfterExit=True
ExecStart=bash -x -c "mount ${root} /sysroot && /usr/lib/ostree/ostree-prepare-root /sysroot && /usr/lib/ostree/ostree-remount /sysroot"
StandardOutput=journal+console
StandardError=journal+console
EOF

ln -s /run/systemd/generator/mount-sysroot.service /run/systemd/generator/initrd-root-fs.target.wants/
exit 0
